### ISSUE TITLE
Add Organizr support

### ISSUE THREAD

**Issue by shaunakkulkarni** [phikai/htpc-docker-standup#7]
It would be awesome if Organizr could be added to this. 

Below is what I think would work in the yaml file- but I am a complete noob at this so im not sure if it right. 

`organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "XXXX:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
	  - VIRTUAL_HOST=organizr.${DOMAIN}
      - LETSENCRYPT_HOST=organizr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}`

**Comment by phikai** [comment]
Right now, I'd say I have no plans for organizr.

That said, when/if an installer ever gets created, this would be a good option for that process so users could select based on their preference.
