### ISSUE TITLE
cp cannot stat 'sample.env' 

### ISSUE THREAD

**Issue by shaunakkulkarni** [phikai/htpc-docker-standup#8]
Hello, 

I followed the installation intructions on ubuntu server 16.04 and I keep getting the above error when i try to copy the sample.env. Am I missing anything? Sorry if its a stupid question but i dont have a lot of experience with linux and docker.

**Comment by shaunakkulkarni** [comment]
nvm, I got it- forgot about the "cd" commannd.  I do have another question though- I got it all installed, but i can't access any of the apps on my domain that i put in the emv.  I got the domain from NameCheap if that makes any difference.

**Comment by phikai** [comment]
Did you configure DNS to point at your server? And do you have ports 80/443 open and forwarding on any firewalls/routers?
